name: Build Pikafish for Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    # 检出代码
    - name: Checkout repository
      uses: actions/checkout@v3

    # 设置 MSVC 环境
    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1

    # 安装依赖（如果需要）
    - name: Install dependencies
      run: |
        choco install make
        choco install mingw
      shell: powershell

    # 下载最新 NNUE 文件
    - name: Download latest NNUE file
      run: |
        curl -L -o pikafish.nnue https://github.com/official-pikafish/Networks/releases/latest/download/pikafish.nnue
      shell: powershell

    # 编译 Pikafish
    - name: Build Pikafish
      run: |
        cd src
        make build ARCH=x86-64-avx2 COMP=msvc
      shell: cmd

    # 打包可执行文件和 NNUE 文件
    - name: Package artifacts
      run: |
        mkdir dist
        copy src\pikafish.exe dist\
        copy pikafish.nnue dist\
        7z a pikafish-windows.zip dist\*
      shell: cmd

    # 上传构建产物
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: pikafish-windows
        path: pikafish-windows.zip
